zk-phi's Dotfiles

* Setup (Mac)

- Open Terminal.app

- Clone this repo and submodules

  : git clone https://github.com/zk-phi/dotfiles.git
  : cd dotfiles
  : git submodule update --init

  You may prompted to accept "Xcode CLI tool" to be installed on your system.

- Install Homebrew (see the official web for the install command)

  BE CAREFUL NOT INSTALL FROM SCAM (FAKE) WEBSITES.

  Note that you may need to add =brew= to =PATH= manually, by following the instructions.

- Install tools via =Brewfile=.

  : cd brew
  : brew bundle

  Some tools may fail to install on Apple Silicon machines. That case, enable Rosetta2 (x86
  emulation layer) to install.

  : arch -x86_64 brew install <tool-name-to-install>

  If asdf says "Bad CPU type in executable", then Rosetta2 may not be installed on your machine. Use
  =softwareupdate= command to install manually that case.

  : softwareupdate --install-rosetta

- Build and install font (or copy from another machine)

  Clone https://github.com/zk-phi/nasucode and follow the instructions to build.

- Create symlinks

  : sh link.sh
  : sudo sh link_sudo.sh

  Make shure to run =link.sh= without =sudo=, so that the created directories belong to the default user.

- Install compilers/interpreters with =asdf=

  : cd asdf
  : sh setup.sh

- (Optional) Change the login shell, iff it's not =zsh= yet

  You probably can skip this step, since recent Mac systems use =zsh= by default.

  : sudo vim /etc/shells # Add /usr/local/bin/zsh
  : chsh -s /usr/local/bin/zsh

(See also https://scrapbox.io/zkphi/Mac_PC_%E7%A7%BB%E8%A1%8C)
