asdf plugin add nodejs
asdf install nodejs 22.12.0
asdf plugin add golang
asdf install golang 1.21.5
asdf plugin add python
asdf install python 2.7.18
asdf install python 3.12.3
asdf plugin add ruby
asdf install ruby 3.4.3
asdf plugin add rust
asdf install rust 1.60.0
